### ISSUE TITLE
Action fails/crashes

### ISSUE THREAD

**Issue by JaapWijnen** [Ilshidur/action-discord#65]
The action sometimes fails with the following error:

```
internal/fs/utils.js:269
9
    throw err;
10
    ^
11

12
Error: ENOENT: no such file or directory, open '/github/workflow/event.json'
13
    at Object.openSync (fs.js:462:3)
14
    at Object.readFileSync (fs.js:364:35)
15
    at Object.<anonymous> (/entrypoint.js:27:25)
16
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
17
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
18
    at Module.load (internal/modules/cjs/loader.js:985:32)
19
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
20
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
21
    at internal/main/run_main_module.js:17:47 {
22
  errno: -2,
23
  syscall: 'open',
24
  code: 'ENOENT',
25
  path: '/github/workflow/event.json'
26
}
```

**Comment by minhchienwikipedia** [comment]
Same issue
